using System;
using System.Text;

namespace Converter
{
    internal class VhdlConverter
    {
        public static string Convert(byte[] binary, string packageName, int width, Endian endian)
        {
            if (width != 8 && width != 16 && width != 32)
            {
                throw new ArgumentOutOfRangeException(nameof(width));
            }

            var builder = new StringBuilder();
            var byteCount = width / 8;
            var length = binary.Length / byteCount;
            if (length * byteCount < binary.Length)
            {
                ++length;
            }
            builder.AppendLine($"-- This file was autogenerated by {Program.Name} - do not edit");
            builder.AppendLine();
            builder.AppendLine("library IEEE;");
            builder.AppendLine("use IEEE.std_logic_1164.all;");
            builder.AppendLine("use IEEE.numeric_std.all;");
            builder.AppendLine();
            builder.AppendLine($"package {packageName} is ");
            builder.AppendLine($"  type {packageName}_data_t is array(0 to {length - 1}) of std_logic_vector({width - 1} downto 0);");
            builder.AppendLine($"  constant {packageName}_data : {packageName}_data_t :=");

            Func<int, byte> read = i => (i < binary.Length ? binary[i] : byte.MinValue);

            switch (width)
            {
                case 8:
                    for (var i = 0; i < length; ++i)
                    {
                        var value = read(i);
                        builder.Append("  ");
                        builder.Append(i == 0 ? "(" : " ");
                        builder.Append($"X\"{value.ToString("X2")}\"");
                        builder.Append(i == length - 1 ? ");" : ",");
                        builder.AppendLine();
                    }
                    break;
                case 16:
                    for (var i = 0; i < length; ++i)
                    {
                        var hi = read(i * 2);
                        var lo = read(i * 2 + 1);
                        var value = (endian == Endian.Big) ? ((hi << 8) | lo) : ((lo << 8) | hi);
                        builder.Append("  ");
                        builder.Append(i == 0 ? "(" : " ");
                        builder.Append($"X\"{value.ToString("X4")}\"");
                        builder.Append(i == length - 1 ? ");" : ",");
                        builder.AppendLine();
                    }
                    break;
                case 32:
                    for (var i = 0; i < length; ++i)
                    {
                        var a = read(i * 4);
                        var b = read(i * 4 + 1);
                        var c = read(i * 4 + 2);
                        var d = read(i * 4 + 3);
                        var value = (endian == Endian.Big) ? ((a << 24) | (b << 16) | (c << 8) | d) : ((d << 24) | (c << 16) | (b << 8) | a);
                        builder.Append("  ");
                        builder.Append(i == 0 ? "(" : " ");
                        builder.Append($"X\"{value.ToString("X8")}\"");
                        builder.Append(i == length - 1 ? ");" : ",");
                        builder.AppendLine();
                    }
                    break;
                default:
                    throw new NotImplementedException($"Conversion for width {width} is not implemented");
            }

            builder.AppendLine("");
            builder.AppendLine($"end {packageName};");

            return builder.ToString();
        }
    }
}